package o;

/* renamed from: o.Ye, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public abstract class AbstractC0627Ye {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;

    /* renamed from: o, reason: collision with root package name */
    public static final long f108o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = TJ.u;
        a = j2;
        b = TJ.c;
        c = TJ.d;
        d = TJ.s;
        long j3 = TJ.D;
        e = j3;
        f = TJ.j;
        long j4 = TJ.f;
        g = j4;
        h = TJ.b;
        i = TJ.a;
        j = TJ.A;
        long j5 = TJ.z;
        k = j5;
        l = j5;
        m = TJ.B;
        n = TJ.G;
        long j6 = TJ.F;
        f108o = j6;
        p = j6;
        q = TJ.H;
        r = j4;
        s = TJ.v;
        t = TJ.M;
        long j7 = TJ.L;
        u = j7;
        v = j7;
        w = TJ.N;
        x = TJ.w;
        y = TJ.x;
        z = TJ.C;
        long j8 = TJ.E;
        A = j8;
        B = j8;
        C = j3;
        D = TJ.e;
        E = TJ.I;
        long j9 = TJ.K;
        F = j9;
        G = j9;
        H = TJ.J;
        I = j2;
        J = j2;
        K = TJ.r;
        L = TJ.q;
        M = TJ.p;
        N = TJ.t;
        O = TJ.g;
        P = TJ.f88o;
        Q = TJ.y;
        R = TJ.O;
        long j10 = TJ.Q;
        S = j10;
        T = j10;
        U = TJ.P;
    }
}
