package o;

/* renamed from: o.bf, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public final class C0802bf {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final long J;
    public final long K;
    public final long L;
    public final long M;
    public final long N;
    public final long O;
    public final long P;
    public final long Q;
    public final long R;
    public final long S;
    public final long T;
    public final long U;
    public final long V;
    public C1978rc W;
    public C1978rc X;
    public C1978rc Y;
    public C1978rc Z;
    public final long a;
    public C1978rc a0;
    public final long b;
    public C1536ld b0;
    public final long c;
    public I00 c0;
    public final long d;
    public C0652Zd d0;
    public final long e;
    public C0331Mu e0;
    public final long f;
    public VA f0;
    public final long g;
    public C2174uD g0;
    public final long h;
    public C2417xY h0;
    public final long i;
    public final long j;
    public final long k;
    public final long l;
    public final long m;
    public final long n;

    /* renamed from: o, reason: collision with root package name */
    public final long f120o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public C0802bf(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.f120o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = j36;
        this.K = j37;
        this.L = j38;
        this.M = j39;
        this.N = j40;
        this.O = j41;
        this.P = j42;
        this.Q = j43;
        this.R = j44;
        this.S = j45;
        this.T = j46;
        this.U = j47;
        this.V = j48;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        GH.k(this.a, sb, "onPrimary=");
        GH.k(this.b, sb, "primaryContainer=");
        GH.k(this.c, sb, "onPrimaryContainer=");
        long j = this.d;
        GH.k(j, sb, "inversePrimary=");
        GH.k(this.e, sb, "secondary=");
        GH.k(this.f, sb, "onSecondary=");
        GH.k(this.g, sb, "secondaryContainer=");
        GH.k(this.h, sb, "onSecondaryContainer=");
        GH.k(this.i, sb, "tertiary=");
        GH.k(this.j, sb, "onTertiary=");
        GH.k(this.k, sb, "tertiaryContainer=");
        GH.k(this.l, sb, "onTertiaryContainer=");
        GH.k(this.m, sb, "background=");
        GH.k(this.n, sb, "onBackground=");
        GH.k(this.f120o, sb, "surface=");
        GH.k(this.p, sb, "onSurface=");
        GH.k(this.q, sb, "surfaceVariant=");
        GH.k(this.r, sb, "onSurfaceVariant=");
        GH.k(this.s, sb, "surfaceTint=");
        GH.k(this.t, sb, "inverseSurface=");
        GH.k(this.u, sb, "inverseOnSurface=");
        GH.k(this.v, sb, "error=");
        GH.k(this.w, sb, "onError=");
        GH.k(this.x, sb, "errorContainer=");
        GH.k(this.y, sb, "onErrorContainer=");
        GH.k(this.z, sb, "outline=");
        GH.k(this.A, sb, "outlineVariant=");
        GH.k(this.B, sb, "scrim=");
        GH.k(this.C, sb, "surfaceBright=");
        GH.k(this.D, sb, "surfaceDim=");
        GH.k(this.E, sb, "surfaceContainer=");
        GH.k(this.F, sb, "surfaceContainerHigh=");
        GH.k(this.G, sb, "surfaceContainerHighest=");
        GH.k(this.H, sb, "surfaceContainerLow=");
        GH.k(this.I, sb, "surfaceContainerLowest=");
        GH.k(this.J, sb, "primaryFixed=");
        GH.k(this.K, sb, "primaryFixedDim=");
        GH.k(this.L, sb, "onPrimaryFixed=");
        GH.k(j, sb, "onPrimaryFixedVariant=");
        GH.k(this.N, sb, "secondaryFixed=");
        GH.k(this.O, sb, "secondaryFixedDim=");
        GH.k(this.P, sb, "onSecondaryFixed=");
        GH.k(this.Q, sb, "onSecondaryFixedVariant=");
        GH.k(this.R, sb, "tertiaryFixed=");
        GH.k(this.S, sb, "tertiaryFixedDim=");
        GH.k(this.T, sb, "onTertiaryFixed=");
        GH.k(this.U, sb, "onTertiaryFixedVariant=");
        sb.append((Object) C0575We.i(this.V));
        sb.append(')');
        return sb.toString();
    }
}
