package o;

/* loaded from: classes.dex */
public enum I8 {
    f("No JAR signatures"),
    g("APK Signature Scheme v1 only supports a maximum of %1$d signers, found %2$d"),
    h("No JAR entries covered by JAR signatures"),
    i("Duplicate entry: %1$s"),
    j("Duplicate section in META-INF/MANIFEST.MF: %1$s"),
    k("Malformed META-INF/MANIFEST.MF: invidual section #%1$d does not have a name"),
    l("Malformed %1$s: invidual section #%2$d does not have a name"),
    m("Missing META-INF/MANIFEST.MF"),
    n("%1$s entry referenced by META-INF/MANIFEST.MF not found in the APK"),
    f33o("No digest for %1$s in META-INF/MANIFEST.MF"),
    p("No digest for %1$s in %2$s"),
    q("%1$s entry not signed"),
    r("Entries %1$s and %3$s are signed with different sets of signers : <%2$s> vs <%4$s>"),
    s("%2$s digest of %1$s does not match the digest specified in %3$s. Expected: <%5$s>, actual: <%4$s>"),
    t("%1$s digest of META-INF/MANIFEST.MF main section does not match the digest specified in %2$s. Expected: <%4$s>, actual: <%3$s>"),
    u("%2$s digest of META-INF/MANIFEST.MF section for %1$s does not match the digest specified in %3$s. Expected: <%5$s>, actual: <%4$s>"),
    v("%1$s does not specify digest of META-INF/MANIFEST.MF. This slows down verification."),
    w("APK is signed using APK Signature Scheme v2 but these signatures may be stripped without being detected because %1$s does not contain anti-stripping protections."),
    x("Partial JAR signature. Found: %1$s, missing: %2$s"),
    y("Failed to verify JAR signature %1$s against %2$s: %3$s"),
    z("JAR signature %1$s uses digest algorithm %5$s and signature algorithm %6$s which is not supported on API Level(s) %4$s for which this APK is being verified"),
    A("Failed to parse JAR signature %1$s: %2$s"),
    /* JADX INFO: Fake field, exist only in values array */
    EF1("Malformed certificate in JAR signature %1$s: %2$s"),
    B("JAR signature %1$s did not verify against %2$s"),
    C("JAR signature %1$s contains no signers"),
    D("Duplicate section in %1$s: %2$s"),
    E("Malformed %1$s: missing Signature-Version attribute"),
    F("JAR signature %1$s references unknown APK signature scheme ID: %2$d"),
    G("JAR signature %1$s indicates the APK is signed using %3$s but no such signature was found. Signature stripped?"),
    H("%1$s not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/."),
    I("No JAR signature from this signer"),
    J("Missing APK Signature Scheme v2 signature required for target sandbox version %1$d"),
    K("Target SDK version %1$d requires a minimum of signature scheme v%2$d; the APK is not signed with this or a later signature scheme"),
    L("No APK Signature Scheme v2 signature from this signer"),
    M("Malformed list of signers"),
    N("Malformed signer block"),
    O("Malformed public key: %1$s"),
    P("Malformed certificate #%2$d: %3$s"),
    Q("Malformed APK Signature Scheme v2 signature record #%1$d"),
    R("Malformed APK Signature Scheme v2 digest record #%1$d"),
    S("Malformed additional attribute #%1$d"),
    T("APK Signature Scheme v2 signer: %1$s references unknown APK signature scheme ID: %2$d"),
    U("APK Signature Scheme v2 signature %1$s indicates the APK is signed using %2$s but no such signature was found. Signature stripped?"),
    V("APK Signature Scheme V2 only supports a maximum of %1$d signers, found %2$d"),
    W("No signers in APK Signature Scheme v2 signature"),
    X("Unknown signature algorithm: %1$#x"),
    Y("Unknown additional attribute: ID %1$#x"),
    Z("Failed to verify %1$s signature: %2$s"),
    a0("%1$s signature over signed-data did not verify"),
    b0("No signatures"),
    c0("No supported signatures: %1$s"),
    d0("No certificates"),
    e0("Public key mismatch between certificate and signature record: <%1$s> vs <%2$s>"),
    f0("Signature algorithms mismatch between signatures and digests records: %1$s vs %2$s"),
    g0("APK integrity check failed. %1$s digest mismatch. Expected: <%2$s>, actual: <%3$s>"),
    h0("Malformed list of signers"),
    i0("Malformed signer block"),
    j0("Malformed public key: %1$s"),
    k0("Malformed certificate #%2$d: %3$s"),
    l0("Malformed APK Signature Scheme v3 signature record #%1$d"),
    m0("Malformed APK Signature Scheme v3 digest record #%1$d"),
    n0("Malformed additional attribute #%1$d"),
    o0("No signers in APK Signature Scheme v3 signature"),
    p0("Multiple APK Signature Scheme v3 signatures found for a single  platform version."),
    q0("Multiple signatures found for pre-v3 signing with an APK  Signature Scheme v3 signer.  Only one allowed."),
    r0("v3 signer differs from v1/v2 signer without proper signing certificate lineage."),
    s0("Unknown signature algorithm: %1$#x"),
    t0("Unknown additional attribute: ID %1$#x"),
    u0("Failed to verify %1$s signature: %2$s"),
    v0("Invalid SDK Version parameter(s) encountered in APK Signature scheme v3 signature: minSdkVersion %1$s maxSdkVersion: %2$s"),
    w0("%1$s signature over signed-data did not verify"),
    x0("No signatures"),
    y0("No supported signatures"),
    z0("No certificates"),
    A0("minSdkVersion mismatch between signed data and signature record: <%1$s> vs <%2$s>"),
    B0("maxSdkVersion mismatch between signed data and signature record: <%1$s> vs <%2$s>"),
    C0("Public key mismatch between certificate and signature record: <%1$s> vs <%2$s>"),
    D0("Signature algorithms mismatch between signatures and digests records: %1$s vs %2$s"),
    E0("APK integrity check failed. %1$s digest mismatch. Expected: <%2$s>, actual: <%3$s>"),
    F0("SigningCertificateLineage attribute containd a proof-of-rotation record with signature(s) that did not verify."),
    G0("Failed to parse the SigningCertificateLineage structure in the APK Signature Scheme v3 signature's additional attributes section."),
    H0("APK signing certificate differs from the associated certificate found in the signer's SigningCertificateLineage."),
    I0("APK Signature Scheme v3 signers supported min/max SDK versions are not continuous."),
    J0("APK Signature Scheme v3 signers supported min/max SDK versions do not cover the entire desired range.  Found min:  %1$s max %2$s"),
    K0("SigningCertificateLineages targeting different platform versions using APK Signature Scheme v3 are not all a part of the same overall lineage."),
    L0("The v3 signer indicates key rotation should be supported starting from SDK version %1$s, but a v3.1 block was not found"),
    M0("The v3 signer indicates key rotation should be supported starting from SDK version %1$s, but the v3.1 block targets %2$s for rotation"),
    N0("APK supports key rotation starting from SDK version %1$s, but the v3 signer does not contain the attribute to detect if this signature is stripped"),
    O0("The APK contains a v3.1 signing block without a v3.0 base block"),
    P0("The rotation-targets-dev-release attribute is only supported on v3.1 signers; this attribute will be ignored by the platform in a v3.0 signer"),
    /* JADX INFO: Fake field, exist only in values array */
    EF3("APK Signing Block contains unknown entry: ID %1$#x"),
    /* JADX INFO: Fake field, exist only in values array */
    EF2("V4 signature has malformed signer block"),
    /* JADX INFO: Fake field, exist only in values array */
    EF3("V4 signature has unknown signing algorithm: %1$#x"),
    /* JADX INFO: Fake field, exist only in values array */
    EF2("V4 signature has no signature found"),
    /* JADX INFO: Fake field, exist only in values array */
    EF3("V4 signature has no supported signature"),
    /* JADX INFO: Fake field, exist only in values array */
    EF2("%1$s signature over signed-data did not verify"),
    /* JADX INFO: Fake field, exist only in values array */
    EF4("Failed to verify %1$s signature: %2$s"),
    /* JADX INFO: Fake field, exist only in values array */
    EF2("Malformed public key: %1$s"),
    /* JADX INFO: Fake field, exist only in values array */
    EF3("V4 signature has malformed certificate"),
    /* JADX INFO: Fake field, exist only in values array */
    EF2("V4 signature has no certificate"),
    /* JADX INFO: Fake field, exist only in values array */
    EF3("V4 signature has mismatched certificate and signature: <%1$s> vs <%2$s>"),
    /* JADX INFO: Fake field, exist only in values array */
    EF2("V4 signature's hash tree root (content digest) did not verity"),
    /* JADX INFO: Fake field, exist only in values array */
    EF3("V4 signature's hash tree did not verity"),
    Q0("V4 signature only supports one signer"),
    R0("V4.1 signature requires two signers"),
    S0("V4 signature and V2/V3 signature have mismatched certificates"),
    T0("V4 signature and V%1$d signature have mismatched digests, V%1$d digest: %2$s, V4 digest: %3$s"),
    U0("V4 signature does not have the expected number of digests, found %1$d"),
    /* JADX INFO: Fake field, exist only in values array */
    EF3("V4 signature format version %1$d is different from the tool's current version %2$d"),
    V0("Neither the source stamp certificate digest file nor the signature block are present in the APK"),
    W0("No SourceStamp signature"),
    X0("Malformed certificate: %1$s"),
    Y0("Malformed SourceStamp signature"),
    Z0("Unknown signature algorithm: %1$#x"),
    a1("Failed to verify %1$s signature: %2$s"),
    b1("%1$s signature over signed-data did not verify"),
    c1("No signature"),
    d1("Signature(s) {%1$s} not supported: %2$s"),
    e1("Certificate mismatch between SourceStamp block in APK signing block and SourceStamp file in APK: <%1$s> vs <%2$s>"),
    f1("A source stamp signature block was found without a corresponding certificate digest in the APK"),
    g1("The source stamp certificate digest in the APK, %1$s, does not match the expected digest, %2$s"),
    h1("Malformed stamp attribute #%1$d"),
    i1("Unknown stamp attribute: ID %1$#x"),
    j1("Failed to parse the SigningCertificateLineage structure in the source stamp attributes section."),
    k1("APK signing certificate differs from the associated certificate found in the signer's SigningCertificateLineage."),
    l1("Source stamp SigningCertificateLineage attribute contains a proof-of-rotation record with signature(s) that did not verify."),
    m1("The source stamp timestamp attribute has an invalid value: %1$d"),
    n1("No digests are available in the source stamp for signature scheme: %1$d"),
    o1("Malformed APK; the following exception was caught when attempting to parse the APK: %1$s"),
    p1("An unexpected exception was caught when verifying the signature: %1$s");

    public final String e;

    I8(String str) {
        this.e = str;
    }
}
